apiVersion: apps/v1
kind: Deployment
metadata:
  name: fragmentui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fragmentui
  template:
    metadata:
      labels:
        app: fragmentui
    spec:
      containers:
        - name: fragmentui
          image: node:18-alpine
          command: ["sh", "-c"]
          args: ["cd /app && npm install && npm start"]
          workingDir: /app
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app-volume
              mountPath: /app
      volumes:
        - name: app-volume
          emptyDir: {}
      initContainers:
        - name: git-clone
          image: alpine/git
          command:
            [
              "git",
              "clone",
              "https://github.com/kelachim/FragmentUI.git",
              "/app",
            ]
          volumeMounts:
            - name: app-volume
              mountPath: /app