apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-module-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-module-app
  template:
    metadata:
      labels:
        app: ui-module-app
    spec:
      containers:
      - name: ui-module-app
        image: node:18-alpine
        command: ["sh", "-c"]
        args: ["cd /app && npm start"]
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: app-volume
          mountPath: /app
      volumes:
      - name: app-volume
        emptyDir: {}
      initContainers:
      - name: git-clone
        image: alpine/git
        command: ["git", "clone", "https://github.com/your-username/your-repo.git", "/app"]
        volumeMounts:
        - name: app-volume
          mountPath: /app